name: Container image build and tag
on:
  push:
    branches:
      - 'main'
      - 's390x-support'
    tags:
      - 'v*'
    paths-ignore:
      - 'LICENSE*'
      - '**.gitignore'
      - '**.md'
      - '**.txt'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/dependabot.yml'
      - 'docs/**'
env:
  IMG_ORG: morana/kubeflow
  IMG_REPO: model-registry
  DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKER_PWD: ${{ secrets.DOCKERHUB_TOKEN }}
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      # Assign context variable for various action contexts (tag, main, CI)
      - name: Assigning tag context
        if: github.head_ref == '' && startsWith(github.ref, 'refs/tags/v')
        run: echo "BUILD_CONTEXT=tag" >> $GITHUB_ENV
      - name: Assigning main context
        if: github.head_ref == '' && github.ref == 'refs/heads/s390x-support'
        run: echo "BUILD_CONTEXT=main" >> $GITHUB_ENV
      # checkout branch
      - uses: actions/checkout@v4
      # set image version
      - name: Set main-branch environment
        if: env.BUILD_CONTEXT == 'main'
        run: |
          commit_sha=${{ github.event.after }}
          tag=main-${commit_sha:0:7}
          echo "VERSION=${tag}" >> $GITHUB_ENV
      - name: Set tag environment
        if: env.BUILD_CONTEXT == 'tag'
        run: |
          echo "VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Quay.io
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME || 'morana' }}
          password: ${{ secrets.QUAY_PASSWORD || 'Cgkc6cGY0aAgyqDboVQceocJuH5Vw7CSs+FZ/x4KDYGTTMSun/eTYydqZqSLw3kPpq8HOeDseHPOcAMEQmwJLA=='}}
      - name: Build and Push Image
        shell: bash
        env:
          BUILD_PUSH_IMAGE: true # multi-arch image is build and pushed
        run: ./scripts/build_deploy.sh
      - name: Tag Latest
        if: env.BUILD_CONTEXT == 'main'
        shell: bash
        env:
          IMG: quay.io/${{ env.IMG_ORG }}/${{ env.IMG_REPO }}
          BUILD_IMAGE: false #image is already built in "Build and Push Image" step
          PUSH_IMAGE: true  #Latest Tag image will be pushed
        run: |
          docker tag ${{ env.IMG }}:$VERSION ${{ env.IMG }}:latest
          # BUILD_IMAGE=false skip the build, just push the tag made above
          VERSION=latest ./scripts/build_deploy.sh
      - name: Tag Main
        if: env.BUILD_CONTEXT == 'main'
        shell: bash
        env:
          IMG: quay.io/${{ env.IMG_ORG }}/${{ env.IMG_REPO }}
          BUILD_IMAGE: false # image is already built in "Build and Push Image" step
          PUSH_IMAGE: true #Main tag image will be pushed 
        run: |
          docker tag ${{ env.IMG }}:$VERSION ${{ env.IMG }}:main
          # BUILD_IMAGE=false skip the build, just push the tag made above
          VERSION=main ./scripts/build_deploy.sh
