name: Build and Push UI and BFF Images
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build from (make sure to use workflow from the same branch).'
        required: true
        type: choice
        options:
        - 's390x-support'
  push:
    branches:
      - 'main'
      - 's390x-support'
    tags:
      - 'v*'
    paths:
      - 'clients/ui/**'
env:
  IMG_ORG: morana/kubeflow
  IMG_UI_REPO: model-registry-ui
  IMG_BFF_REPO: model-registry-bff
  DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKER_PWD: ${{ secrets.DOCKERHUB_TOKEN }}
  BUILD_PUSH_IMAGE: true # multi-arch image is build and pushed
  BUILD_IMAGE: false 
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      # Assign context variable for various action contexts (main, CI)
      - name: Assigning main context
        if: github.head_ref == '' && github.ref == 'refs/heads/s390x-support'
        run: echo "BUILD_CONTEXT=main" >> $GITHUB_ENV
      # checkout branch
      - uses: actions/checkout@v4
      # set image version
      - name: Set main-branch environment
        if: env.BUILD_CONTEXT == 'main'
        run: |
          commit_sha=${{ github.event.after }}
          tag=main-${commit_sha:0:7}
          echo "VERSION=${tag}" >> $GITHUB_ENV
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Quay.io
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME || 'morana' }}
          password: ${{ secrets.QUAY_PASSWORD || 'Cgkc6cGY0aAgyqDboVQceocJuH5Vw7CSs+FZ/x4KDYGTTMSun/eTYydqZqSLw3kPpq8HOeDseHPOcAMEQmwJLA=='}}
      - name: Build and Push UI Image
        shell: bash
        env:
          IMG_REPO: ${{ env.IMG_UI_REPO }}
        run: ./scripts/build_deploy.sh
      - name: Build and Push BFF Image
        shell: bash
        env:
          IMG_REPO: ${{ env.IMG_BFF_REPO }}
        run: ./scripts/build_deploy.sh
      - name: Tag Latest UI Image
        if: env.BUILD_CONTEXT == 'main'
        shell: bash
        env:
          IMG_REPO: ${{ env.IMG_UI_REPO }}
          IMG: ${{ env.IMG_ORG }}/${{ env.IMG_UI_REPO }}
        run: VERSION=latest ./scripts/build_deploy.sh
      - name: Tag Latest BFF Image
        if: env.BUILD_CONTEXT == 'main'
        shell: bash
        env:
          IMG_REPO: ${{ env.IMG_BFF_REPO }}
          IMG: ${{ env.IMG_ORG }}/${{ env.IMG_BFF_REPO }}
        run: VERSION=latest ./scripts/build_deploy.sh
